---
- name: this playbook will call different role #new test line
  hosts: serverg
  tasks:
  
          - name: this will call role
            ansible.builtin.include_role:
                name: /root/user-role/roles
