---
- name: this playbook will call different role
  hosts: serverg
  vars_files:
    - vars/
  tasks:
          - name: this will call role
            ansible.builtin.include_role:
                name: roles
            
